### ISSUE TITLE
Bug: Transaction not unset when dropping a flush when sampling

### ISSUE THREAD

**Issue by hxnk** [inspector-apm/inspector-php#13]
I believe that when returning false on a beforeFlush callback, the transaction should be unset as well (line 300)

https://github.com/inspector-apm/inspector-php/blob/dca0f05c6800a38abd540f517cddd786a2a2711d/src/Inspector.php#L283-L306

**Comment by ilvalerione** [comment]
Hi Henk,
can you help me to understand the bug? Why is the missing "unset" a problem? Has an error occurred in your application?

**Comment by hxnk** [comment]
Hi!

When running a continuous process like a queue worker that picks up jobs (at least when using Laravel), and a beforeCallback returns false for a specific job (meaning that it should not be reported), the inspector keeps a reference to that transaction (because it is not unset in that scenario, only when actually being flushed (line 305)).

When the next execution starts, because the inspector still holds a reference the transaction of the previous disregarded execution it's not being replaced with the new one, and that one will be flushed (or disregarded again).

**Comment by ilvalerione** [comment]
I just released the fix:

https://github.com/inspector-apm/inspector-php/releases/tag/3.7.18

You only need `composer update` to get it.
