### ISSUE TITLE
Check aliases and abbreviations for ignored commands

### ISSUE THREAD

**Issue by tacman** [inspector-apm/inspector-php#21]
Ignoring a commad should check for aliases and short names.   I like to run

```
bin/console d:m:m -n
```

because it's shorter to type.  but #20 still happens, unless I run it with the complete command:

```
bin/console doctrine:migration:migrate -n
```

Obviously, I can add every alias to the ignore list, but it seems like the application should look up the command and then check if the full command name is on the list.

**Comment by ilvalerione** [comment]
For this issue we are on the wrong repository. It's related to https://github.com/inspector-apm/inspector-symfony

Anyway I got the point, but the way we prefer develop the package is avoiding hidden automations that developers can't customize or interact with. This is why we prefer to use the builtin ignore_commands property that is efficient and transparent if devs want to change something.

We will add short version of commands in the config file of the recipe.
