### ISSUE TITLE
AbstractApiTransport::sendViaFile incorrect $filePath?

### ISSUE THREAD

**Issue by mailopl** [inspector-apm/inspector-php#5]
Hello,

Using:
```
$filepath = __DIR__.DIRECTORY_SEPARATOR.uniqid().'.dat';
file_put_contents($filepath, $json, LOCK_EX);
```
makes inspector to generate path like:
 `/var/www/project/vendor/inspector-apm/inspector-php/src/Transports/randomName.dat`
 which is causing me access issues.
I can of course fix permissions manually, but this made me wondering if this is really the path you want to store the .dat files in? 
Wouldn't using say /tmp/ be a better choice perhaps?

And thank you for the product, it's neat.

**Comment by ilvalerione** [comment]
Hi @mailopl in Unix systems "sendViaFile()" call should be extremely rare. 
It is thought mainly for win based machines (often when you test inspector for the first time in your personal PC) that accept a very limited number of characters in a single terminal command, so using files is the only way I found to attach the payload to the CURL request.

Is it happening in a Unix machine in your case?

**Comment by mailopl** [comment]
@ilvalerione yes it does indeed on Ubuntu, this seems to be part calling it:
```
if ($jsonLength > $this->config->getMaxPostSize()) {
    if ($count === 1) {
        // It makes no sense to divide into chunks, just try to send via file
        return $this->sendViaFile($json); // <----------------------------------- here 
    }
```

**Comment by ilvalerione** [comment]
Are you using the Laravel package?
What kind of transactions are you trying to trace? Http, commands?

**Comment by mailopl** [comment]
Yes it's laravel package 4.6.20.
I can get you projectId 2491 and timestamp if you want to verify - 16 Apr 12:47:52. 

Possible issue might be super long transaction timeline in the log, this may be reason why max post size gets exceeded.

**Comment by ilvalerione** [comment]
The release 3.7.0 use the `/tmp` directory for temporary files.
