### ISSUE TITLE
Fix Inspector::isRecording()

### ISSUE THREAD

**Issue by smilesrg** [inspector-apm/inspector-php#8]
https://github.com/inspector-apm/inspector-symfony/issues/4

Methods `canAddSegment()` and `isRecording()` are needed to be replaced with this code:

```php

    /**
     * Determine if a new segment can be added.
     *
     * @return bool
     */
    public function canAddSegments(): bool
    {
        return $this->isRecording();
    }

    /**
     * Check if a transaction was started.
     *
     * @return bool
     */
    public function isRecording(): bool
    {
        return $this->configuration->isEnabled() && $this->hasTransaction();
    }

```

**Comment by ilvalerione** [comment]
Hi @smilesrg the code you are referencing isn't the code of the latest version.

In the latest version (3.6.0) the implementation of the "isRecording" method is different: https://github.com/inspector-apm/inspector-php/blob/3.6.0/src/Inspector.php#L147

**Comment by smilesrg** [comment]
@ilvalerione I provided the code, that should be used instead of current methods :-) I don't have an access to the repo, so I can't create PR

**Comment by ilvalerione** [comment]
You could verify if other methods can be suitable for your use case like `hasTransaction()` or `needTransaction()` methods or use a combination of them to perform your desired check.

e.g. https://github.com/inspector-apm/inspector-laravel/blob/master/src/Providers/CommandServiceProvider.php#L33

**Comment by ilvalerione** [comment]
Also this is not a "fix", it sould be marked as a change request, I would be grateful if you could change the title of the issue.

**Comment by smilesrg** [comment]
The description of the method `isRecording()` is `Check if a transaction was started.` but it actually checks if Inspector is enabled in the config. It is confusing. You can clone https://github.com/smilesrg/symfony-inspector-example-app and install it by running `composer install `, it leads to an error:

https://github.com/inspector-apm/inspector-symfony/issues/4

**Comment by ilvalerione** [comment]
Other than an error due to the wrong "api_key" config value: In InspectorExtension.php line 27

it doesn't fire any error

![Immagine](https://user-images.githubusercontent.com/13559278/118113898-28e75a80-b3e7-11eb-87f0-b89141efb80e.png)

**Comment by smilesrg** [comment]
Because you need to create a file `.env.local` and put the configuration key there:
```
INSPECTOR_INGESTION_KEY='yourKeyHere'
```

Pease do a `git pull` with my latest changes and try again

**Comment by ilvalerione** [comment]
I close this because it's not related to a bug in the inspector-php package, but it's about a bug in the inspector-symfony

https://github.com/inspector-apm/inspector-symfony/issues/4
