### ISSUE TITLE
Add possibility to get inspector's segment by label

### ISSUE THREAD

**Issue by smilesrg** [inspector-apm/inspector-php#9]
I need to get Segment by a label to develop https://github.com/inspector-apm/inspector-symfony properly.

I need to end the segment in some methods, but I can't pass the segment instance itself directly to the method.

Use-case: start segment in `onKernelRequest()` and finish it in `onKernelResponse()`

So, I need the method `public function getSegment(string $type, string $label)` I'm not sure which role has the `type` parameter here, but probably, segments are grouped by types?

**Comment by ilvalerione** [comment]
This thread is related to the inspector-symfony repository

**Comment by smilesrg** [comment]
@ilvalerione I need a new method implementation in https://github.com/inspector-apm/inspector-php/blob/master/src/Inspector.php it's related to this repository
